spring:
  cloud:
    gateway:
      routes:
        - id: route_qq
          uri: http://www.qq.com
          predicates:
            - Query=url,qq
        - id: route_baidu
          uri: http://www.baidu.com
          predicates:
            - Query=url,baidu
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: passjava-gateway
server:
  port: 8006

