#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.188.128:3306/passjava_cms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 199418
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.188.128:8848
#  application:
#    name: passjava-content
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#
#server:
#  port: 8007
#
#
#
#
